# This file is used to define the rules for how lists are supposed to operate
# This is the Default YAML. Anything defined in here will be defined for every game

#Something is "Exclusive" if there can only be one of it in either excluded/included
#Something is "Non-Exclusive" if you can have the same thing multiple times

# This section will make that list tab be filled with all "items" defined by the datapackage
# Lists are defined by Square Brackets: []
List Items:
  Exclusive: ["local_items", "non_local_items", "item_links"]
  Non-Exclusive: ["start_hints"]

# This section will make that list tab be filled with all "locations" defined by the datapackage
# Lists are defined by Square Brackets: []
List Locations:
  Exclusive: ["start_location_hints", "priority_locations", "exclude_locations"]
  Non-Exclusive: []

# This section will make that dictionary tab be filled with all "items" defined by the datapackage
# Lists are defined by Square Brackets: []
Dictionary Items:
  Exclusive: []
  Non-Exclusive: ["start_inventory", "start_inventory_from_pool"]

# This section will make that dictionary tab be filled with all "locations" defined by the datapackage
# Lists are defined by Square Brackets: []
Dictionary Locations:
  Exclusive: []
  Non-Exclusive: []