name: Build and Release EXE

on:
  push:
    branches:
      - main
  release:
    types: [created]  # Triggers on GitHub Release creation

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --add-data "Setup;Setup" --add-data "YAML;YAML" yaml_editor.py

      - name: Upload EXE as Artifact (For GitHub Actions)
        uses: actions/upload-artifact@v4
        with:
          name: yaml_editor_exe
          path: dist/yaml_editor.exe

      - name: Upload EXE to GitHub Release (If Release Created)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/yaml_editor.exe
