name: Build and Release EXE

on:
  push:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pyinstaller pyyaml PyQt5

      - name: Build Executable
        run: |
          pyinstaller --onefile --add-data "Datapackages;Datapackages" mainwindow.py

      - name: Package EXE into ZIP
        run: |
          mkdir release
          mv dist/mainwindow.exe release/mainwindow.exe
          cd release
          powershell -Command "Compress-Archive -Path mainwindow.exe -DestinationPath mainwindow.zip"

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mainwindow
          path: release/mainwindow.zip

      - name: Upload ZIP to GitHub Release (If Release Created)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: release/mainwindow.zip
