name: Build and Release EXE

on:
  push:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pyinstaller pyyaml PySide6

      - name: Build Executable
        run: |
          pyinstaller --name "YAML_Editor" --onefile --collect-submodules PySide6 --hidden-import=yaml --add-data "Datapackages;Datapackages" mainwindow.py

      - name: Move Build into yaml_editor Folder
        run: |
          mkdir yaml_editor
          mkdir yaml_editor/release
          mv dist yaml_editor/dist
          mv "yaml_editor/dist/YAML_Editor.exe" "yaml_editor/release/YAML_Editor.exe"
          cd yaml_editor/release
          powershell -Command "Compress-Archive -Path 'YAML_Editor.exe' -DestinationPath 'YAML_Editor.zip'"

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YAML_Editor
          path: yaml_editor/release/YAML_Editor.zip

      - name: Upload ZIP to GitHub Release (If Release Created)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: yaml_editor/release/YAML_Editor.zip
