name: Build and Release EXE

on:
  push:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pyinstaller pyyaml  # Ensure PyYAML is installed

      - name: Build Executable
        run: |
          pyinstaller --onefile --hidden-import=yaml --add-data "Setup;Setup" --add-data "YAML;YAML" yaml_editor.py

      - name: Package EXE into ZIP
        run: |
          mkdir release
          mv dist/yaml_editor.exe release/yaml_editor.exe
          cd release
          powershell -Command "Compress-Archive -Path yaml_editor.exe -DestinationPath yaml_editor.zip"

      - name: Upload EXE as Artifact (For GitHub Actions)
        uses: actions/upload-artifact@v4
        with:
          name: yaml_editor
          path: dist/yaml_editor.exe

      - name: Upload ZIP as Artifact (For GitHub Actions)
        uses: actions/upload-artifact@v4
        with:
          name: yaml_editor_zip
          path: release/yaml_editor.zip

      - name: Upload EXE & ZIP to GitHub Release (If Release Created)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/yaml_editor.exe
            release/yaml_editor.zip
